apiVersion: v1
kind: Pod
metadata: 
  name: pod-restartpolicy
  namespace: dev
spec:
  containers:
  - name: nginx
    image: nginx:1.17.1
    ports:
    - name: nginx-port
      containerPort: 80
    livenessProbe:
      httpGet:
        path: /
        port: 80
        host: 10.1.0.50
        scheme: HTTP
  restartPolicy: Never