#http://localhost:30003/
apiVersion: v1
kind: Service
metadata:
  name: service-volume-emptydir
  namespace: dev
spec:
  selector:
    app: volume-emptydir-pod
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30003
