#kd -n dev logs -f volume-emptydir-855b7f4d89-f6cps  -c busybox 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: volume-emptydir
  namespace: dev
  labels:
    controller: deploy
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: volume-emptydir-pod
  template:
    metadata:
      labels: 
        app: volume-emptydir-pod
    spec:
      containers:
      - name: nginx
        image: nginx:1.17.1
        ports:
        - name: nginx-port
          containerPort: 80
        volumeMounts:
        - name: logs-volume
          mountPath: /var/log/nginx
      - name: busybox
        image: busybox:1.30
        command: ["/bin/sh", "-c", "tail -f /logs/access.log"]
        volumeMounts:
        - name: logs-volume
          mountPath: /logs
      volumes:
      - name: logs-volume
        emptyDir: {}