#kd -n dev delete -f volume-hostpath.yaml
#kd -n dev logs -f volume-emptydir-855b7f4d89-f6cps  -c busybox 
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: pvc1
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: pvc2
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: pvc3
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi