#kd -n dev scale deploy pc-deployment --replicas=3
#kd -n dev set image deploy pc-deployment nginx=nginx:1.17.2
#kd -n dev apply -f pc-deployment-records.yaml --record 
#kd -n dev rollout status deploy pc-deployment-recreate
#kd -n dev rollout history deploy pc-deployment-recreate
#kd -n dev rollout undo deploy pc-deployment-undo --to-revision=1
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: pc-deployment-undo
  namespace: dev
  labels:
    controller: deploy
spec:
  replicas: 3
  revisionHistoryLimit: 3
  paused: false
  progressDeadlineSeconds: 600
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 30%
  selector: 
    matchLabels:
      app: nginx-pod
  template:
    metadata:
      labels:
        app: nginx-pod
    spec:
      containers:
      - name: nginx
        image: nginx:1.17.1
        ports:
        - name: nginx-port
          containerPort: 80