#kd -n dev apply -f pc-cronjob.yaml
#kd -n dev get pod -o wide | grep cro
#kd -n dev get pod -w | grep cro
#kd -n dev get job -w
#kd -n dev get cronjob -o wide
apiVersion: batch/v1beta1
kind: CronJob
metadata: 
  name: pc-cronjob
  namespace: dev
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    metadata:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: counter-pod
            image: busybox:1.30
            command: ["bin/sh", "-c", "for i in 9 8 7 6 5 4 3 2 1; do echo $i; sleep 3; done"]