# kd taint nodes docker-desktop tag=carl:NoSchedule
apiVersion: v1
kind: Pod
metadata: 
  name: pod-toleration-noschedule-nginxpod
  namespace: dev
spec:
  containers:
  - name: nginx
    image: nginx:1.17.1
    ports:
    - name: nginx-port
      containerPort: 80
  tolerations:
  - key: "tag"
    operator: "Equal"
    value: "carl"
    effect: "NoSchedule"