#kd -n dev apply -f cm-deployment.yaml
#kd exec -it cm-deployment-79b989fc64-7xspc /bin/sh -n dev
#
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: cm-deployment
  namespace: dev
  labels:
    controller: deploy
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: volume-emptydir-pod
  template:
    metadata:
      labels: 
        app: volume-emptydir-pod
    spec:
      containers:
      - name: nginx
        image: nginx:1.17.1
        ports:
        - name: nginx-port
          containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /configmap/config
      volumes:
      - name: config
        configMap:
          name: configmap