apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-for-storageclass
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: managed-nfs-storage		#和storage-class.yaml中的provisioner保持一致
  resources:
    requests:
      storage: 500Mi

