apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"creationTimestamp":"2023-03-21T15:10:43Z","name":"nginxpod","namespace":"dev","resourceVersion":"342775","uid":"a4399214-024e-4138-8d6b-a47a68a6a995"},"spec":{"containers":[{"image":"nginx:1.17.1","imagePullPolicy":"IfNotPresent","name":"nginx-containers","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/var/run/secrets/kubernetes.io/serviceaccount","name":"kube-api-access-hgjsq","readOnly":true},{"mountPath":"/etc/secrets","name":"secrets"}]}],"dnsPolicy":"ClusterFirst","enableServiceLinks":true,"initContainers":[{"command":["sh","-c","until ping 127.0.0.1 -c 1 ; do echo waiting  for mysql...; sleep 200; done;"],"image":"busybox:1.30","name":"test-mysql"},{"command":["sh","-c","until ping 127.0.0.1 -c 1 ; do echo waiting  for mysql...; sleep 200; done;"],"image":"busybox:1.30","name":"test-mysql1"}],"nodeName":"docker-desktop","preemptionPolicy":"PreemptLowerPriority","priority":0,"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"serviceAccount":"default","serviceAccountName":"default","terminationGracePeriodSeconds":30,"tolerations":[{"effect":"NoExecute","key":"node.kubernetes.io/not-ready","operator":"Exists","tolerationSeconds":300},{"effect":"NoExecute","key":"node.kubernetes.io/unreachable","operator":"Exists","tolerationSeconds":300}],"volumes":[{"name":"kube-api-access-hgjsq","projected":{"defaultMode":420,"sources":[{"serviceAccountToken":{"expirationSeconds":3607,"path":"token"}},{"configMap":{"items":[{"key":"ca.crt","path":"ca.crt"}],"name":"kube-root-ca.crt"}},{"downwardAPI":{"items":[{"fieldRef":{"apiVersion":"v1","fieldPath":"metadata.namespace"},"path":"namespace"}]}}]}},{"name":"secrets","secret":{"secretName":"mysecret"}}]},"status":{"conditions":[{"lastProbeTime":null,"lastTransitionTime":"2023-03-21T15:10:43Z","status":"True","type":"Initialized"},{"lastProbeTime":null,"lastTransitionTime":"2023-03-21T15:10:44Z","status":"True","type":"Ready"},{"lastProbeTime":null,"lastTransitionTime":"2023-03-21T15:10:44Z","status":"True","type":"ContainersReady"},{"lastProbeTime":null,"lastTransitionTime":"2023-03-21T15:10:43Z","status":"True","type":"PodScheduled"}],"containerStatuses":[{"containerID":"docker://3b9c7cbefc8510c50cb7fa52f7270f1b467dd88c9ee88205f37868d5dd5c933a","image":"nginx:1.17.1","imageID":"docker-pullable://nginx@sha256:b4b9b3eee194703fc2fa8afa5b7510c77ae70cfba567af1376a573a967c03dbb","lastState":{},"name":"nginx-containers","ready":true,"restartCount":0,"started":true,"state":{"running":{"startedAt":"2023-03-21T15:10:43Z"}}}],"hostIP":"192.168.65.4","phase":"Running","podIP":"10.1.0.32","podIPs":[{"ip":"10.1.0.32"}],"qosClass":"BestEffort","startTime":"2023-03-21T15:10:43Z"}}
  creationTimestamp: "2023-04-04T15:43:06Z"
  labels:
    podenv: testlabel
  name: nginxpod
  namespace: dev
  resourceVersion: "1193698"
  uid: 30eda5e4-2159-4d5f-a972-7943bbdbc3de
spec:
  containers:
  - image: nginx:1.17.1
    imagePullPolicy: IfNotPresent
    name: nginx-containers
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-hgjsq
      readOnly: true
    - mountPath: /etc/secrets
      name: secrets
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
  - command:
    - sh
    - -c
    - until ping 127.0.0.1 -c 1 ; do echo waiting  for mysql...; sleep 200; done;
    image: busybox:1.30
    imagePullPolicy: IfNotPresent
    name: test-mysql
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-hgjsq
      readOnly: true
  - command:
    - sh
    - -c
    - until ping 127.0.0.1 -c 1 ; do echo waiting  for mysql...; sleep 200; done;
    image: busybox:1.30
    imagePullPolicy: IfNotPresent
    name: test-mysql1
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-hgjsq
      readOnly: true
  nodeName: docker-desktop
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-hgjsq
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
  - name: secrets
    secret:
      defaultMode: 420
      secretName: mysecret
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-04-04T15:43:08Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-04-04T15:43:09Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-04-04T15:43:09Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-04-04T15:43:06Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://43b1b16253061e2ba1af925f93aebc7c3e81f07496dcfd3919b56e06ed2d6e32
    image: nginx:1.17.1
    imageID: docker-pullable://nginx@sha256:b4b9b3eee194703fc2fa8afa5b7510c77ae70cfba567af1376a573a967c03dbb
    lastState: {}
    name: nginx-containers
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-04-04T15:43:08Z"
  hostIP: 192.168.65.4
  initContainerStatuses:
  - containerID: docker://9e04692d6508d10cbe244d9fc1e66686bf182c8c3921022124913b9cbea7bf3a
    image: busybox:1.30
    imageID: docker-pullable://busybox@sha256:4b6ad3a68d34da29bf7c8ccb5d355ba8b4babcad1f99798204e7abb43e54ee3d
    lastState: {}
    name: test-mysql
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: docker://9e04692d6508d10cbe244d9fc1e66686bf182c8c3921022124913b9cbea7bf3a
        exitCode: 0
        finishedAt: "2023-04-04T15:43:07Z"
        reason: Completed
        startedAt: "2023-04-04T15:43:07Z"
  - containerID: docker://14841a1f6aa2b8bd58d32ceb693f3c63eee1229e436a31ff495c0de240b69422
    image: busybox:1.30
    imageID: docker-pullable://busybox@sha256:4b6ad3a68d34da29bf7c8ccb5d355ba8b4babcad1f99798204e7abb43e54ee3d
    lastState: {}
    name: test-mysql1
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: docker://14841a1f6aa2b8bd58d32ceb693f3c63eee1229e436a31ff495c0de240b69422
        exitCode: 0
        finishedAt: "2023-04-04T15:43:07Z"
        reason: Completed
        startedAt: "2023-04-04T15:43:07Z"
  phase: Running
  podIP: 10.1.0.39
  podIPs:
  - ip: 10.1.0.39
  qosClass: BestEffort
  startTime: "2023-04-04T15:43:06Z"
