apiVersion: v1
kind: Pod
metadata: 
  name: pod-schedule-nodeselector
  namespace: dev
spec:
  containers:
  - name: nginx
    image: nginx:1.17.1
    ports:
    - name: nginx-port
      containerPort: 80
  nodeSelector:
    nodeenv: testlabel
    #nodeenv: testlabel1